//
//  MonitorConfigBuilder.swift
//  BtnQ
//
//  Turns the wizard's learned results into a MonitorConfig. The control KIND and
//  option labels/values come from the ControlTemplate; only the VCP code (and,
//  for ranges, the max) was discovered. Skipped controls are simply absent from
//  the input and so never appear in the output.
//

import Foundation

/// One control the wizard successfully learned (auto-detected or taught).
struct LearnedControl {
    let template: ControlTemplate
    let code: UInt8
    /// The range max read from the monitor (ignored for cycles/toggles).
    let max: UInt16
    /// For cycles: the discrete options discovered on this monitor (from the
    /// capabilities list and observation), already labeled. Falls back to the
    /// template's options when nil.
    var options: [ControlTemplate.OptionTemplate]? = nil
}

enum MonitorConfigBuilder {
    /// `extras` are controls auto-filled from a known profile (a taught control
    /// always wins on a stateKey clash). When `orderedLike` is given, the result
    /// follows that profile's layout — its group/section headers and control order
    /// — with our taught/auto-filled controls slotted into their matching
    /// positions; anything we have that the profile doesn't is appended. This is
    /// how a recognized monitor gets the familiar grouped menu instead of a flat
    /// list. With no profile, controls are taught-order then extras.
    static func build(name: String, learned: [LearnedControl], extras: [Control] = [],
                      orderedLike profile: MonitorConfig? = nil,
                      edid: [MonitorConfig.EDIDMatch]? = nil) -> MonitorConfig {
        let taughtControls = learned.map(control(for:))
        let taughtKeys = Set(taughtControls.map(\.stateKey))
        let extraControls = extras.filter { !taughtKeys.contains($0.stateKey) }

        let controls: [Control]
        if let profile {
            var byKey: [String: Control] = [:]
            for c in taughtControls + extraControls where !c.isHeader && byKey[c.stateKey] == nil {
                byKey[c.stateKey] = c   // taught listed first, so it wins
            }
            var result: [Control] = []
            var used = Set<String>()
            for control in profile.controls {
                if control.isHeader { result.append(control); continue }   // keep grouping
                if let mine = byKey[control.stateKey] { result.append(mine); used.insert(control.stateKey) }
            }
            for c in taughtControls + extraControls where !c.isHeader && !used.contains(c.stateKey) {
                result.append(c); used.insert(c.stateKey)
            }
            controls = result
        } else {
            // No profile to mirror → arrange into sensible default groups with dividers.
            controls = grouped(taughtControls + extraControls)
        }

        return MonitorConfig(
            name: name,
            match: [name],
            edid: edid,
            controls: disableVolumeWhenMuted(hideColorTemperatureInSRGB(controls)),
            comment: "Generated by Didact (Set Up This Monitor). Verify the controls work, then consider sharing it so others with this monitor benefit.",
            schemaVersion: 1)
    }

    /// Default menu grouping for a freshly-taught monitor (no curated profile to
    /// mirror). Controls are bucketed by label into these ordered groups, separated
    /// by dividers; anything unrecognised (e.g. discovered MCCS extras) keeps its
    /// order in a final group. The user can rearrange afterwards in Edit Menu.
    private static let defaultGroups: [[String]] = [
        ["Moon Halo", "Moon Halo Brightness", "Moon Halo Color Temperature", "Moon Halo Light Mode"],
        ["Night Mode", "Night Level", "Low Blue Light", "Sensitivity", "Auto Brightness"],
        ["Color Mode", "Brightness", "Contrast", "Sharpness", "Color Temperature"],
        ["Audio Mute", "Volume"],
        ["Source", "Input Select"],
    ]

    private static func grouped(_ controls: [Control]) -> [Control] {
        let real = controls.filter { !$0.isHeader }
        func matches(_ c: Control, _ name: String) -> Bool { c.label?.caseInsensitiveCompare(name) == .orderedSame }
        var used = Set<Int>()
        var buckets: [[Control]] = []
        for group in defaultGroups {
            var bucket: [Control] = []
            for name in group {
                for (i, c) in real.enumerated() where !used.contains(i) && matches(c, name) {
                    bucket.append(c); used.insert(i)
                }
            }
            if !bucket.isEmpty { buckets.append(bucket) }
        }
        let leftovers = real.enumerated().filter { !used.contains($0.offset) }.map(\.element)
        if !leftovers.isEmpty { buckets.append(leftovers) }

        var out: [Control] = []
        for (i, bucket) in buckets.enumerated() {
            if i > 0 { out.append(Control(kind: .section)) }   // divider between groups
            out.append(contentsOf: bucket)
        }
        return out
    }

    /// sRGB is a fixed colour space (D65 white point), so colour temperature does
    /// nothing while it's selected. If we have both a Colour Mode with an sRGB option
    /// and a Colour Temperature control, hide the latter while the former is sRGB.
    private static func hideColorTemperatureInSRGB(_ controls: [Control]) -> [Control] {
        guard let colorMode = controls.first(where: {
                  $0.kind == .cycle && $0.label?.caseInsensitiveCompare("Color Mode") == .orderedSame }),
              let code = colorMode.vcp,
              let srgb = colorMode.options?.first(where: {
                  $0.label.range(of: "sRGB", options: .caseInsensitive) != nil })?.value
        else { return controls }
        return controls.map { control in
            guard control.kind == .cycle,
                  control.label?.caseInsensitiveCompare("Color Temperature") == .orderedSame,
                  control.hideWhen == nil else { return control }
            var copy = control
            copy.hideWhen = Control.Condition(vcp: code, equals: srgb)
            return copy
        }
    }

    /// A muted output has nothing to adjust, so disable Volume while Audio Mute is
    /// on. Wired up whenever both an Audio Mute toggle and a Volume control exist.
    private static func disableVolumeWhenMuted(_ controls: [Control]) -> [Control] {
        guard let mute = controls.first(where: {
                  $0.kind == .toggle && $0.label?.caseInsensitiveCompare("Audio Mute") == .orderedSame }),
              let code = mute.vcp, let on = mute.onValue
        else { return controls }
        return controls.map { control in
            guard control.kind == .range,
                  control.label?.caseInsensitiveCompare("Volume") == .orderedSame,
                  control.disableWhen == nil else { return control }
            var copy = control
            copy.disableWhen = Control.Condition(vcp: code, equals: on)
            return copy
        }
    }

    private static func control(for item: LearnedControl) -> Control {
        let t = item.template
        let vcp = HexValue(Int(item.code))
        switch t.kind {
        case .range:
            let max = item.max > 0 ? Int(item.max) : (t.fallbackMax ?? 100)
            return Control(kind: .range, label: t.label, vcp: vcp, min: t.suggestedMin ?? 0, max: max,
                           hideWhen: t.hideWhenHDR ? Control.Condition(system: "hdr") : nil)
        case .cycle:
            let source = item.options ?? t.options
            let options = source?.map {
                // An HDR pseudo-option has no DDC value; it toggles macOS HDR.
                Control.Option(value: $0.hdr ? nil : HexValue($0.value), label: $0.label, hdr: $0.hdr ? true : nil)
            }
            return Control(kind: .cycle, label: t.label, vcp: vcp, options: options,
                           noRead: t.noRead ? true : nil, noVerify: t.noVerify ? true : nil)
        case .toggle:
            return Control(kind: .toggle, label: t.label, vcp: vcp,
                           onValue: t.onValue.map(HexValue.init), offValue: t.offValue.map(HexValue.init),
                           noRead: t.noRead ? true : nil)
        case .group, .section:
            return Control(kind: t.kind, label: t.label)
        }
    }

    /// The stateKey the built control for this learned item will have — used to
    /// dedupe taught controls against auto-filled extras.
    static func stateKey(for item: LearnedControl) -> String { control(for: item).stateKey }

    /// Codes mapped to more than one control — almost always a mis-press the user
    /// should review before saving.
    static func duplicateCodes(_ learned: [LearnedControl]) -> [UInt8] {
        var counts: [UInt8: Int] = [:]
        for item in learned { counts[item.code, default: 0] += 1 }
        return counts.filter { $0.value > 1 }.keys.sorted()
    }
}
